largura = float(input("Qual a largura da parede?"))
altura = float(input("Qual a altura da parede?"))
area = (largura * altura)
tinta = (area / 2)
print(f"A área a ser pintada será de {area} e a quantidade de tinta necessária para o serviço será de {tinta} litros.")